# Generated by Django 3.1.2 on 2020-10-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201013_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_caroussel',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='producteurs',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
