# Generated by Django 3.1.2 on 2020-10-13 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201013_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_caroussel',
            old_name='name',
            new_name='title',
        ),
    ]
